server:
  port: 8082

spring:
  profiles:
    active: dev

---

spring:
  application:
    name: chat-service
  profiles: dev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

---

spring:
  profiles: test

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false