server:
  port: 8090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      preferSameZoneEureka: true
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication/**

        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**
