version: '3'
services:
  game-service:
    build: server/game-service
    ports:
      - "8081:8081"
    restart: always

  chat-service:
    build: server/chat-service
    ports:
      - "8082:8082"
    restart: always

  authentication-service:
    build: server/authentication-service
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "chess"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: