version: '3'
services:
  game-service:
    build: server/game-service
    ports:
      - "8081:8081"
    restart: always

  chat-service:
    build: server/chat-service
    ports:
      - "8082:8082"
    restart: always