server:
  port: 8084

spring:
  application:
    name: queue-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

kafka:
  bootstrap-servers: localhost:9092