server:
  port: 8084

kafka-topics:
  start-game: start-game

spring:
  profiles:
    active: dev

---

spring:
  application:
    name: queue-service
  kafka:
    bootstrap-servers: localhost:9092
  profiles: dev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

---

spring:
  profiles: test

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


