server:
  port: 8083

spring:
  profiles:
    active: dev
---

spring:
  profiles : test

  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
     datasource:
      username: sa
      password: sa

---
spring:
  application:
    name: authentication-service
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mysql://localhost:3306/chess"
    username: "root"
    password: "password"

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost