server:
  port: 8083

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/chess"
    username: "root"
    password: "password"

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000