server:
  port: 8081

spring:
  application:
    name: game-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost