server:
  port: 8085

kafka-topics:
  game-history: game-history

spring:
  profiles:
    active: dev
---

spring:
  profiles : test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

---
spring:
  application:
    name: history-service
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/chess
    username: "root"
    password: "password"
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
