name: Test

on: [push]

jobs:

  app-tests:
    name: App tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
        working-directory: ./app
      - name: Run tests
        run: npm run test:cov
        working-directory: ./app
      - name: Upload coverage
        uses: codecov/codecov-action@v
        env:
          CI: true

  game-service-tests:
    name: Game service tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./server/game-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn verify
        working-directory: ./server/game-service
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true

  chat-service-tests:
    name: Chat service tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./server/chat-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn verify
        working-directory: ./server/chat-service
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true

  authentication-service-tests:
    name: Authentication service tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./server/authentication-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn verify
        working-directory: ./server/authentication-service
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true

  queue-service-tests:
    name: Queue service tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./server/queue-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn verify
        working-directory: ./server/queue-service
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true

  history-service-tests:
    name: History service tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./server/history-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn verify
        working-directory: ./server/history-service
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true